using BudgetManagerLibrary.Business_Objects;
using Dapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

namespace BudgetManagerLibrary
{
    /// <summary>
    /// A class to manage writing and reading to and from a SQL database in Microsoft SSMS using Stored Procedures.
    /// </summary>
    public class SQLconnector : IDataConnection
    {
        // CHANGE DATABASE NAME if using a different one:
        private const string DatabaseName = "BudgetManagerDB";

        /// <summary>
        /// Saves a new budget to the database.
        /// </summary>
        /// <param name="budget">Budget object to be saved</param>
        /// <returns>Budget object with a new unique identifier generated by the database</returns>
        public Budget SaveBudget(Budget budget)
        {
            // establish the connection:
            using (IDbConnection connection = new System.Data.SqlClient.SqlConnection(GlobalConfig.CnnString(DatabaseName)))
            {
                var p = new DynamicParameters();
                /* passing the parameters for the stored procedure in the server manager spBudget_Insert  */
                /* first, store all parameters to be passed in a var p: */
                p.Add("@budgetName", budget.Name);
                p.Add("@balance", budget.Balance);
                // we are getting the id back here:
                p.Add("@id", 0, dbType: DbType.Int32, direction: ParameterDirection.Output);

                /* using Execute method, pass the stored procedure name, var p (all of the parameters) and a command type: */
                connection.Execute("dbo.spBudget_Insert", p, commandType: CommandType.StoredProcedure);

                /* save the id in the budget using Get<dataType>(@SQL parameter name) : */
                budget.Id = p.Get<int>("@id");

                return budget;
            }
        }
        /// <summary>
        /// Get a list of budgets currently stored in the database.
        /// </summary>
        /// <returns>List of Budget objects</returns>
        public List<Budget> GetBudgets()
        {
            List<Budget> output;
            using (IDbConnection connection = new System.Data.SqlClient.SqlConnection(GlobalConfig.CnnString(DatabaseName)))
            {
                output = connection.Query<Budget>("dbo.spBudget_GetAll").ToList();
            }
            return output;
        }

        /// <summary>
        /// Edit a specified budget's balance.
        /// </summary>
        /// <param name="budgetId">Budget ID</param>
        /// <param name="budgetBalance">New budget balance</param>
        public void EditBudgetBalance(int budgetId, decimal budgetBalance)
        {
            // establish the connection:
            using (IDbConnection connection = new System.Data.SqlClient.SqlConnection(GlobalConfig.CnnString(DatabaseName)))
            {
                var p = new DynamicParameters();
                /* first, store all parameters to be passed in a var p: */
                p.Add("@budgetId", budgetId);
                p.Add("@newBalance", budgetBalance);

                /* using Execute method, pass the stored procedure name, var p (all of the parameters) and a command type: */
                connection.Execute("dbo.spEditBudgetBalance", p, commandType: CommandType.StoredProcedure);
            }
        }

        /// <summary>
        /// Delete a specified budget from the database.
        /// </summary>
        /// <param name="budgetId">Budget'd ID</param>
        public void DeleteBudget(int budgetId)
        {
            using (IDbConnection connection = new System.Data.SqlClient.SqlConnection(GlobalConfig.CnnString(DatabaseName)))
            {
                var p = new DynamicParameters();
                p.Add("@delBudgetId", budgetId);

                connection.Execute("dbo.spDeleteBudgetAll", p, commandType: CommandType.StoredProcedure);
            }
        }
        /// <summary>
        /// Get a list of entries stored in the database for a specific budget, sorted by date (descending).
        /// </summary>
        /// <param name="budgetId">Budget ID</param>
        /// <returns>List of Entry objects</returns>
        public List<Entry> GetEntriesByDate(int budgetId)
        {
            List<Entry> output;
            using (IDbConnection connection = new System.Data.SqlClient.SqlConnection(GlobalConfig.CnnString(DatabaseName)))
            {
                var p = new DynamicParameters();
                /* first, store all parameters to be passed in a var p: */
                p.Add("@budgetId", budgetId);

                output = connection.Query<Entry>("dbo.spEntry_GetByDate", p, commandType: CommandType.StoredProcedure).ToList();
            }
            return output;
        }
        /// <summary>
        /// Save a new entry to a database.
        /// </summary>
        /// <param name="entry">Entry object to be saved</param>
        /// <returns>Entry object with a new unique identifier generated by the database.</returns>
        public Entry SaveEntry(Entry entry)
        {
            using (IDbConnection connection = new System.Data.SqlClient.SqlConnection(GlobalConfig.CnnString(DatabaseName)))
            {
                var p = new DynamicParameters();
                p.Add("@entryName", entry.Name);
                p.Add("@entryAmount", entry.Amount);
                p.Add("@entryCategory", entry.Category);
                p.Add("@entryDate", entry.Date);
                p.Add("@entryBudgetId", entry.BudgetID);
                // get the ID back:
                p.Add("@id", 0, dbType: DbType.Int32, direction: ParameterDirection.Output);

                connection.Execute("dbo.spEntry_Insert", p, commandType: CommandType.StoredProcedure);
                entry.Id = p.Get<int>("@id");

                return entry;
            }
        }

        /// <summary>
        /// Get a total spent per specified month.
        /// </summary>
        /// <param name="month">Month</param>
        /// <param name="budgetId">Budget ID</param>
        /// <returns>A total spent per month</returns>
        public decimal GetSpendByMonth(int month, int budgetId)
        {
            decimal monthlySpent = 0;
            using (IDbConnection connection = new System.Data.SqlClient.SqlConnection(GlobalConfig.CnnString(DatabaseName)))
            {
                var p = new DynamicParameters();
                p.Add("@month", month);
                p.Add("@budgetId", budgetId);
                p.Add("@expenses", 0, dbType: DbType.Decimal, direction: ParameterDirection.Output);

                connection.Execute("dbo.spGetExpensesByMonth", p, commandType: CommandType.StoredProcedure);
                try
                {
                    monthlySpent = p.Get<decimal>("@expenses");
                    return monthlySpent;
                }
                catch
                {
                    return 0;
                }                
            }
        }
        /// <summary>
        /// Delete an entry from the database.
        /// </summary>
        /// <param name="entry">Entry object to be deleted</param>
        public void DeleteEntry(Entry entry )
        {
            using (IDbConnection connection = new System.Data.SqlClient.SqlConnection(GlobalConfig.CnnString(DatabaseName)))
            {
                var p = new DynamicParameters();
                p.Add("@delEntryId", entry.Id);

                connection.Execute("dbo.spDeleteEntry", p, commandType: CommandType.StoredProcedure);
            }
        }
    }
}
